language: csharp
sudo: required

services:
  - docker
before_script:
#script:
    - chmod +x buildServer.sh
    - ./buildServer.sh build-local
    - ./buildServer.sh build-docker
   # - ./buildServer run-docker
script:
   - ./buildServer.sh run-integration-docker
