language: csharp
sudo: required

services:
  - docker
#before_script:
script:
    - chmod +x buildServer
    - ./buildServer build-local
    - ./buildServer build-docker
   # - ./buildServer run-docker
#script:
   # - ./buildServer unit-local
   # - ./buildServer integration-local
