#! /bin/bash
docker run --name gamescoreboarddb -p 3306:3306 -e MYSQL_DATABASE=gamescoreboarddb -e MYSQL_ROOT_PASSWORD=passord1 -d mysql
sleep 10
docker run -it --link gamescoreboarddb:mysql --rm -v $(pwd):/opt/ mysql sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD" gamescoreboarddb < /opt/createGameScoreboardDatabase.sql'
